// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKS24JZluX7ooddzX9qWw0xR3GKrjdPP0',
    appId: '1:840164516520:web:0ada98166723ecb039989d',
    messagingSenderId: '840164516520',
    projectId: 'qwe-mynotes',
    authDomain: 'qwe-mynotes.firebaseapp.com',
    storageBucket: 'qwe-mynotes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIGgi2X6JOwvyD8pJsIdVcXJUS3RzFHY',
    appId: '1:840164516520:android:a733fdc0196dbd2639989d',
    messagingSenderId: '840164516520',
    projectId: 'qwe-mynotes',
    storageBucket: 'qwe-mynotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlTw10g_ykCPYzEaXrnMMcUsJwhdG5yxE',
    appId: '1:840164516520:ios:a48335f2917af40b39989d',
    messagingSenderId: '840164516520',
    projectId: 'qwe-mynotes',
    storageBucket: 'qwe-mynotes.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlTw10g_ykCPYzEaXrnMMcUsJwhdG5yxE',
    appId: '1:840164516520:ios:a48335f2917af40b39989d',
    messagingSenderId: '840164516520',
    projectId: 'qwe-mynotes',
    storageBucket: 'qwe-mynotes.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKS24JZluX7ooddzX9qWw0xR3GKrjdPP0',
    appId: '1:840164516520:web:352eb55626b8a8fc39989d',
    messagingSenderId: '840164516520',
    projectId: 'qwe-mynotes',
    authDomain: 'qwe-mynotes.firebaseapp.com',
    storageBucket: 'qwe-mynotes.firebasestorage.app',
  );
}
